/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhc_myapplication_Jni */

#ifndef _Included_com_fhc_myapplication_Jni
#define _Included_com_fhc_myapplication_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhc_myapplication_Jni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fhc_myapplication_Jni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fhc_myapplication_Jni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fhc_myapplication_Jni_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fhc_myapplication_Jni
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_fhc_myapplication_Jni_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
